<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Microprojects.Edm.Host</RootNamespace>
    <AssemblyName>Microprojects.Edm.Host</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\EdmAssemblyInfo.cs" Link="Properties\EdmAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.71.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Certificate" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.2" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Edm\Edm.csproj" />
    <ProjectReference Include="..\Microprojects.Edm.Shared\Microprojects.Edm.Shared.csproj" />
  </ItemGroup>

</Project>
