export default {
    action: {
        delete: 'Delete',
        deleteFor: 'Delete {{type}}',
        viewMode: 'View mode',
        editMode: 'Edit mode',
        outdatedEdit: 'Outdated — open the current version to edit',
        copy: 'Copy',
        close: 'Close',
        cancel: 'Cancel',
        saveChanges: 'Save Changes',
        lockedBy: 'Locked by {{name}}',
    },
    badge: {
        lockedBy: '🔒 Locked by {{name}}',
        outdated: 'outdated',
        outdatedTooltip: 'A newer version exists. This record is preserved for historical references and cannot be edited.',
    },
    dialog: {
        delete: {
            confirmPrompt: 'Permanently delete <0>{{name}}</0>? This action cannot be undone.',
        },
    },
    toast: {
        fallbackName: 'Item',
        deleted: '{{name}} deleted',
        copied: 'Copied',
        copyFailed: 'Copy failed',
        saved: 'Saved',
        savedAsNewVersion: 'Saved as a new version',
        created: 'Created',
    },
    editor: {
        forkDefaultDetail: 'This change will create a new version.',
        forkConfirm: '{{detail}}\n\nProceed and create a new version?',
        forkTitle: 'Create new version?',
        forkAction: 'Create version',
    },
    title: {
        newItem: 'New Item',
    },
    error: {
        saveFailed: 'Save failed',
        deleteFailed: 'Delete failed',
    },
    entityPlural: {
        item: 'Items',
        order: 'Orders',
        supply: 'Supplies',
        folder: 'Folders',
        tare: 'Tares',
        taretype: 'Tare types',
        nomenclature: 'Nomenclatures',
        process: 'Processes',
        workplace: 'Workplaces',
        host: 'Hosts',
        device: 'Devices',
    },
    folder: {
        identity: 'Identity',
        name: 'Name',
        nameMissing: 'Folder name is required',
        nameHelp: 'Folder name shown in the tree and in the breadcrumb',
        description: 'Description',
        accessControl: 'Access control',
        restrictedAccess: 'Restricted access',
        openToEveryone: 'Open to everyone',
        openBanner: 'Anyone with platform access can see this folder and its contents.',
        restrictedNote_one: '{{count}} group can view this folder.',
        restrictedNote_few: '{{count}} groups can view this folder.',
        restrictedNote_many: '{{count}} groups can view this folder.',
        openNote: 'Add a group to restrict who can see this folder.',
        groups: 'Groups',
        addAnotherGroup: 'Add another group…',
        leaveEmptyOpen: 'Leave empty to keep this folder open to everyone',
        emptyMeansEveryone: 'When the list is empty, <0>everyone</0> with platform access can see this folder.',
    },
} as const
