syntax = "proto3";

option csharp_namespace = "Optosense.Edm.WebApi";

package Edm;

service JobExecutor {
  rpc ExecuteJob(JobParams) returns (JobResponse);
  rpc GetAvailableTasks (AvalableTaskParams) returns (AvailableTasks);
}

// The request message containing the user's name.
message JobParams {
	string job = 1;
	string params = 2;
}

message JobResponse {
	string status = 1;
	string message = 2;
	string response = 3;
}
 
message AvalableTaskParams {

}

message AvailableTasks {
	
	message Task {
		string TaskName = 1;
        string Status = 2;
        string Type = 3;
        string Pid = 4;
	}

	repeated Task tasks = 1;
}