// <auto-generated />
using System;
using Microprojects.Edm.Ui.Logistics.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Microprojects.Edm.Ui.Logistics.Persistence.Migrations
{
    [DbContext(typeof(LogisticsContext))]
    [Migration("20250501181722_ItemWithMeta")]
    partial class ItemWithMeta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NomenclatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Changelog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Changelog");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Directory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DirectoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryId");

                    b.ToTable("Directories");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.History", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MetaId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NomenclatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OriginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SerialNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipmentExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TareId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("OriginId");

                    b.HasIndex("TareId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Meta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Groups")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metatype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meta");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Nomenclature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<Guid?>("DefaultTareTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DirectoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultTareTypeId");

                    b.HasIndex("DirectoryId");

                    b.ToTable("Nomenclatures");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DirectoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Specification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Specifications");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.SpecificationNomenclature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NomenclatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SpecificationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("SpecificationId");

                    b.ToTable("SpecificationNomenclatures");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.SubProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LinkedProcessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LinkedProcessId");

                    b.HasIndex("ProcessId");

                    b.ToTable("SubProcesses", (string)null);
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Tare", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TareTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TareTypeId");

                    b.ToTable("Tares");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.TareType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("Countable")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dimensions")
                        .HasColumnType("int");

                    b.Property<Guid?>("DirectoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryId");

                    b.ToTable("TareTypes");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Assignment", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Nomenclature", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomenclature");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Directory", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Directory", "Directory")
                        .WithMany("Children")
                        .HasForeignKey("DirectoryId");

                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Meta", "Meta")
                        .WithOne()
                        .HasForeignKey("Microprojects.Edm.Ui.Logistics.Models.Directory", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Directory");

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.History", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Meta", "Meta")
                        .WithMany("History")
                        .HasForeignKey("MetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Item", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Meta", "Meta")
                        .WithOne()
                        .HasForeignKey("Microprojects.Edm.Ui.Logistics.Models.Item", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Nomenclature", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Item", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId");

                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Tare", "Tare")
                        .WithMany()
                        .HasForeignKey("TareId");

                    b.Navigation("Meta");

                    b.Navigation("Nomenclature");

                    b.Navigation("Origin");

                    b.Navigation("Tare");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Nomenclature", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.TareType", "DefaultTareType")
                        .WithMany()
                        .HasForeignKey("DefaultTareTypeId");

                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Directory", "Directory")
                        .WithMany()
                        .HasForeignKey("DirectoryId");

                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Meta", "Meta")
                        .WithOne()
                        .HasForeignKey("Microprojects.Edm.Ui.Logistics.Models.Nomenclature", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DefaultTareType");

                    b.Navigation("Directory");

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Process", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Directory", "Directory")
                        .WithMany()
                        .HasForeignKey("DirectoryId");

                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Meta", "Meta")
                        .WithOne()
                        .HasForeignKey("Microprojects.Edm.Ui.Logistics.Models.Process", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Directory");

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.SpecificationNomenclature", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Nomenclature", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Specification", "Specification")
                        .WithMany("Row")
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomenclature");

                    b.Navigation("Specification");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.SubProcess", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Process", "LinkedProcess")
                        .WithMany()
                        .HasForeignKey("LinkedProcessId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Process", "Process")
                        .WithMany("SubProcesses")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LinkedProcess");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Tare", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.TareType", "TareType")
                        .WithMany()
                        .HasForeignKey("TareTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TareType");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.TareType", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Directory", "Directory")
                        .WithMany()
                        .HasForeignKey("DirectoryId");

                    b.HasOne("Microprojects.Edm.Ui.Logistics.Models.Meta", "Meta")
                        .WithOne()
                        .HasForeignKey("Microprojects.Edm.Ui.Logistics.Models.TareType", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Directory");

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Directory", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Meta", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Process", b =>
                {
                    b.Navigation("SubProcesses");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Logistics.Models.Specification", b =>
                {
                    b.Navigation("Row");
                });
#pragma warning restore 612, 618
        }
    }
}
