using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Microprojects.Edm.Ui.Logistics.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class SeedDirectoryStructure : Migration
    {
        // Root must be Guid.Empty (matches Directory.GeneralRootId).
        // All other Ids were pre-generated by UUIDNext (Uuid.NewDatabaseFriendly(Database.SqlServer))
        // so they are stable across migration applications and friendly to SQL Server clustered indexes.
        private static readonly Guid RootId = Guid.Empty;

        private static readonly Guid NomenclaturesDirId    = new("7f1791e2-0028-89ac-9cce-019dd417d015");
        private static readonly Guid NomenclatureExampleId = new("42ddf5c4-9655-867d-8d8b-019dd417d01a");

        private static readonly Guid ProcessesDirId      = new("42ce3e02-7df3-8870-8d8c-019dd417d01a");
        private static readonly Guid ManufactureDirId    = new("803b11f2-cb55-8145-8d8d-019dd417d01a");
        private static readonly Guid TechnologyDirId     = new("701f3747-9162-86e3-8d8e-019dd417d01a");
        private static readonly Guid OperationDirId      = new("6bd8cdcf-a47f-8a55-8d8f-019dd417d01a");
        private static readonly Guid ManufactureProcessId = new("6bcbfcbf-70c7-8042-8d90-019dd417d01a");
        private static readonly Guid TechnologyProcessId  = new("ba187e10-c632-81a3-8d91-019dd417d01a");
        private static readonly Guid OperationProcessId   = new("5330e2c4-6995-82b9-8d92-019dd417d01a");

        private static readonly Guid SpecificationsDirId    = new("ea259495-613d-808c-8d93-019dd417d01a");
        private static readonly Guid SpecificationExampleId = new("fbb0a4f3-c727-879e-8d94-019dd417d01a");

        private static readonly Guid TareTypesDirId    = new("d75940b0-f8f7-8fca-8d95-019dd417d01a");
        private static readonly Guid TareTypeExampleId = new("e359ab5d-8be0-8c9e-8d96-019dd417d01a");

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($@"
-- ===== Root =====
IF NOT EXISTS (SELECT 1 FROM [Meta] WHERE [Id] = '{RootId}')
    INSERT INTO [Meta] ([Id], [Metatype], [Owner], [Groups], [Created])
    VALUES ('{RootId}', 'Directory', 'system', '[]', SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM [Directories] WHERE [Id] = '{RootId}')
    INSERT INTO [Directories] ([Id], [Name], [DirectoryId])
    VALUES ('{RootId}', 'Root', NULL);

-- ===== Nomenclatures folder + example =====
IF NOT EXISTS (SELECT 1 FROM [Meta] WHERE [Id] = '{NomenclaturesDirId}')
    INSERT INTO [Meta] ([Id], [Metatype], [Owner], [Groups], [Created])
    VALUES ('{NomenclaturesDirId}', 'Directory', 'system', '[]', SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM [Directories] WHERE [Id] = '{NomenclaturesDirId}')
    INSERT INTO [Directories] ([Id], [Name], [DirectoryId])
    VALUES ('{NomenclaturesDirId}', 'Nomenclatures', '{RootId}');

IF NOT EXISTS (SELECT 1 FROM [Meta] WHERE [Id] = '{NomenclatureExampleId}')
    INSERT INTO [Meta] ([Id], [Metatype], [Owner], [Groups], [Created])
    VALUES ('{NomenclatureExampleId}', 'Nomenclature', 'system', '[]', SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM [Nomenclatures] WHERE [Id] = '{NomenclatureExampleId}')
    INSERT INTO [Nomenclatures] ([Id], [Name], [DirectoryId], [Category], [Countable], [DefaultTareTypeId])
    VALUES ('{NomenclatureExampleId}', 'Nomenclature (example)', '{NomenclaturesDirId}', 0, 1, NULL);

-- ===== Processes folder + 3 kind subfolders + example processes =====
IF NOT EXISTS (SELECT 1 FROM [Meta] WHERE [Id] = '{ProcessesDirId}')
    INSERT INTO [Meta] ([Id], [Metatype], [Owner], [Groups], [Created])
    VALUES ('{ProcessesDirId}', 'Directory', 'system', '[]', SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM [Directories] WHERE [Id] = '{ProcessesDirId}')
    INSERT INTO [Directories] ([Id], [Name], [DirectoryId])
    VALUES ('{ProcessesDirId}', 'Processes', '{RootId}');

IF NOT EXISTS (SELECT 1 FROM [Meta] WHERE [Id] = '{ManufactureDirId}')
    INSERT INTO [Meta] ([Id], [Metatype], [Owner], [Groups], [Created])
    VALUES ('{ManufactureDirId}', 'Directory', 'system', '[]', SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM [Directories] WHERE [Id] = '{ManufactureDirId}')
    INSERT INTO [Directories] ([Id], [Name], [DirectoryId])
    VALUES ('{ManufactureDirId}', 'Manufacture', '{ProcessesDirId}');

IF NOT EXISTS (SELECT 1 FROM [Meta] WHERE [Id] = '{TechnologyDirId}')
    INSERT INTO [Meta] ([Id], [Metatype], [Owner], [Groups], [Created])
    VALUES ('{TechnologyDirId}', 'Directory', 'system', '[]', SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM [Directories] WHERE [Id] = '{TechnologyDirId}')
    INSERT INTO [Directories] ([Id], [Name], [DirectoryId])
    VALUES ('{TechnologyDirId}', 'Technology', '{ProcessesDirId}');

IF NOT EXISTS (SELECT 1 FROM [Meta] WHERE [Id] = '{OperationDirId}')
    INSERT INTO [Meta] ([Id], [Metatype], [Owner], [Groups], [Created])
    VALUES ('{OperationDirId}', 'Directory', 'system', '[]', SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM [Directories] WHERE [Id] = '{OperationDirId}')
    INSERT INTO [Directories] ([Id], [Name], [DirectoryId])
    VALUES ('{OperationDirId}', 'Operation', '{ProcessesDirId}');

IF NOT EXISTS (SELECT 1 FROM [Meta] WHERE [Id] = '{ManufactureProcessId}')
    INSERT INTO [Meta] ([Id], [Metatype], [Owner], [Groups], [Created])
    VALUES ('{ManufactureProcessId}', 'Process', 'system', '[]', SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM [Processes] WHERE [Id] = '{ManufactureProcessId}')
    INSERT INTO [Processes] ([Id], [Name], [DirectoryId], [Kind], [NomenclatureId])
    VALUES ('{ManufactureProcessId}', 'Manufacture (example)', '{ManufactureDirId}', 0, NULL);

IF NOT EXISTS (SELECT 1 FROM [Meta] WHERE [Id] = '{TechnologyProcessId}')
    INSERT INTO [Meta] ([Id], [Metatype], [Owner], [Groups], [Created])
    VALUES ('{TechnologyProcessId}', 'Process', 'system', '[]', SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM [Processes] WHERE [Id] = '{TechnologyProcessId}')
    INSERT INTO [Processes] ([Id], [Name], [DirectoryId], [Kind], [NomenclatureId])
    VALUES ('{TechnologyProcessId}', 'Technology (example)', '{TechnologyDirId}', 1, NULL);

IF NOT EXISTS (SELECT 1 FROM [Meta] WHERE [Id] = '{OperationProcessId}')
    INSERT INTO [Meta] ([Id], [Metatype], [Owner], [Groups], [Created])
    VALUES ('{OperationProcessId}', 'Process', 'system', '[]', SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM [Processes] WHERE [Id] = '{OperationProcessId}')
    INSERT INTO [Processes] ([Id], [Name], [DirectoryId], [Kind], [NomenclatureId])
    VALUES ('{OperationProcessId}', 'Operation (example)', '{OperationDirId}', 2, NULL);

-- ===== Specifications folder + example (linked to Manufacture process) =====
IF NOT EXISTS (SELECT 1 FROM [Meta] WHERE [Id] = '{SpecificationsDirId}')
    INSERT INTO [Meta] ([Id], [Metatype], [Owner], [Groups], [Created])
    VALUES ('{SpecificationsDirId}', 'Directory', 'system', '[]', SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM [Directories] WHERE [Id] = '{SpecificationsDirId}')
    INSERT INTO [Directories] ([Id], [Name], [DirectoryId])
    VALUES ('{SpecificationsDirId}', 'Specifications', '{RootId}');

IF NOT EXISTS (SELECT 1 FROM [Meta] WHERE [Id] = '{SpecificationExampleId}')
    INSERT INTO [Meta] ([Id], [Metatype], [Owner], [Groups], [Created])
    VALUES ('{SpecificationExampleId}', 'Specification', 'system', '[]', SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM [Specifications] WHERE [Id] = '{SpecificationExampleId}')
    INSERT INTO [Specifications] ([Id], [Name], [DirectoryId], [Active], [ProcessId])
    VALUES ('{SpecificationExampleId}', 'Specification (example)', '{SpecificationsDirId}', 0, '{ManufactureProcessId}');

-- ===== TareTypes folder + example =====
IF NOT EXISTS (SELECT 1 FROM [Meta] WHERE [Id] = '{TareTypesDirId}')
    INSERT INTO [Meta] ([Id], [Metatype], [Owner], [Groups], [Created])
    VALUES ('{TareTypesDirId}', 'Directory', 'system', '[]', SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM [Directories] WHERE [Id] = '{TareTypesDirId}')
    INSERT INTO [Directories] ([Id], [Name], [DirectoryId])
    VALUES ('{TareTypesDirId}', 'TareTypes', '{RootId}');

IF NOT EXISTS (SELECT 1 FROM [Meta] WHERE [Id] = '{TareTypeExampleId}')
    INSERT INTO [Meta] ([Id], [Metatype], [Owner], [Groups], [Created])
    VALUES ('{TareTypeExampleId}', 'TareType', 'system', '[]', SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM [TareTypes] WHERE [Id] = '{TareTypeExampleId}')
    INSERT INTO [TareTypes] ([Id], [Name], [DirectoryId], [Units], [Capacity], [Countable], [SizeX], [SizeY], [SizeZ])
    VALUES ('{TareTypeExampleId}', 'TareType (example)', '{TareTypesDirId}', '', 1, 1, NULL, NULL, NULL);
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($@"
-- Delete child entities before their parent directories, and Meta last.
DELETE FROM [Specifications] WHERE [Id] = '{SpecificationExampleId}';
DELETE FROM [Processes]      WHERE [Id] IN ('{ManufactureProcessId}', '{TechnologyProcessId}', '{OperationProcessId}');
DELETE FROM [Nomenclatures]  WHERE [Id] = '{NomenclatureExampleId}';
DELETE FROM [TareTypes]      WHERE [Id] = '{TareTypeExampleId}';

-- Leaf directories first (kind subfolders), then top-level entity folders, then Root.
DELETE FROM [Directories] WHERE [Id] IN ('{ManufactureDirId}', '{TechnologyDirId}', '{OperationDirId}');
DELETE FROM [Directories] WHERE [Id] IN ('{NomenclaturesDirId}', '{ProcessesDirId}', '{SpecificationsDirId}', '{TareTypesDirId}');
DELETE FROM [Directories] WHERE [Id] = '{RootId}';

DELETE FROM [Meta] WHERE [Id] IN (
    '{RootId}',
    '{NomenclaturesDirId}', '{NomenclatureExampleId}',
    '{ProcessesDirId}', '{ManufactureDirId}', '{TechnologyDirId}', '{OperationDirId}',
    '{ManufactureProcessId}', '{TechnologyProcessId}', '{OperationProcessId}',
    '{SpecificationsDirId}', '{SpecificationExampleId}',
    '{TareTypesDirId}', '{TareTypeExampleId}'
);
");
        }
    }
}
