<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AdaptiveExpressions" Version="4.23.0" />
    <PackageReference Include="System.IO.Ports" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Edm\Edm.csproj" />
    <ProjectReference Include="..\Optosense.Edm.Core\Optosense.Edm.Core.csproj" />
  </ItemGroup>

</Project>
