<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AdaptiveExpressions" Version="4.22.2" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="System.Reactive.Linq" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Edm\Edm.csproj" />
    <ProjectReference Include="..\Optosense.Edm.DataAccess\Optosense.Edm.DataAccess.csproj" />
    <ProjectReference Include="..\Optosense.Edm.Domain\Optosense.Edm.Domain.csproj" />
  </ItemGroup>

</Project>
