<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Edm\Protos\job.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AdaptiveExpressions" Version="4.23.0" />
    <PackageReference Include="Google.Protobuf" Version="3.33.1" />
    <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Edm\Edm.csproj" />
    <ProjectReference Include="..\Optosense.Edm.Core\Optosense.Edm.Core.csproj" />
    <ProjectReference Include="..\Optosense.Edm.Domain\Optosense.Edm.Domain.csproj" />
    <ProjectReference Include="..\Optosense.Edm\Optosense.Edm.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Edm\Protos\job.proto" />
  </ItemGroup>

</Project>
    