<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Microprojects.Edm</RootNamespace>
    <AssemblyName>Microprojects.Edm.Shared</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\EdmAssemblyInfo.cs" Link="Properties\EdmAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AdaptiveExpressions" Version="4.23.1" />
    <PackageReference Include="AutoMapper" Version="[14.0.0]" />
    <PackageReference Include="Google.Protobuf" Version="3.33.1" />
    <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.IO.Ports" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Edm\Edm.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Grpc\job.proto" />
  </ItemGroup>

</Project>
