<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	<OutputType>Library</OutputType>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ui\build\**" />
    <Compile Remove="ui\node_modules\**" />
    <EmbeddedResource Include="ui\build\**" />
    <EmbeddedResource Remove="ui\node_modules\**" />
    <None Remove="ui\build\**" />
    <None Remove="ui\node_modules\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="ui\.env.local" />
    <None Remove="ui\.eslintcache" />
    <None Remove="ui\.gitignore" />
    <None Remove="ui\yarn-error.log" />
    <None Remove="ui\yarn.lock" />
    <None Remove="ui\*.local" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.EventLog" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Edm\Edm.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ui\src\components\" />
  </ItemGroup>

</Project>
