<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>

    <UserSecretsId>d5dbdbac-1012-4ec0-ab12-a38b5ec3bb72</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="AdaptiveExpressions" Version="4.23.1" />
	  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client" Version="1.5.377.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microprojects.Edm.Shared\Microprojects.Edm.Shared.csproj" />
    <ProjectReference Include="..\Microprojects.Edm.Ui.Logistics\Microprojects.Edm.Ui.Logistics.csproj" />
    <ProjectReference Include="..\Microprojects.Edm.Ui.Technologies\Microprojects.Edm.Ui.Technologies.csproj" />
    <ProjectReference Include="..\Optosense.Edm.Plugins.OpcUa\Optosense.Edm.Plugins.OpcUa.csproj" />
    <ProjectReference Include="..\Optosense.Edm.Profiles.Board\Optosense.Edm.Profiles.Board.csproj" />
  </ItemGroup>

</Project>
