<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <OutputType>Library</OutputType>
    <DefaultItemExcludes>$(DefaultItemExcludes);</DefaultItemExcludes>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ui\build\**" />
    <Compile Remove="ui\node_modules\**" />
    <EmbeddedResource Remove="ui\node_modules\**" />
    <EmbeddedResource Include="ui\build\**" />
    <None Remove="ui\build\**" />
    <None Remove="ui\node_modules\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="ui\.env.development.local" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Optosense.Edm\Optosense.Edm.csproj" />
  </ItemGroup>

</Project>
