<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <PublishReadyToRun>true</PublishReadyToRun>
	  <PublishSingleFile>true</PublishSingleFile>
	  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
	  <PublishDir>bin\$(Configuration)\$(TargetFramework)\$(RuntimeIdentifier)\publish\</PublishDir>
    <InvariantGlobalization>true</InvariantGlobalization>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

</Project>
