// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microprojects.Edm.Ui.Technologies.Persistence;

namespace Microprojects.Edm.Ui.Technologies.Persistence.Migrations
{
    [DbContext(typeof(TechnologiesContext))]
    [Migration("20210315081412_ProcessOperation")]
    partial class ProcessOperation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Rules")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.AuditCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Arg1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Arg2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Args")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Param")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("AuditCriteria");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.AuditZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AuditId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("No")
                        .HasColumnType("int");

                    b.Property<int>("Offset")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.ToTable("AuditZones");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DriverGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Host", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.HostDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("HostId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("HostId");

                    b.ToTable("HostDevices");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("Cancelled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Scheduled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkbenchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkbenchId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.OperationHostDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("HostDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HostDeviceId");

                    b.HasIndex("OperationId");

                    b.HasIndex("ProfileId");

                    b.ToTable("OperationHostDevices");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OperationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProfilerGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.ProfilePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<long>("Offset")
                        .HasColumnType("bigint");

                    b.Property<string>("Operation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfilePoint");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperationHostDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Request")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationHostDeviceId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Workbench", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkplaceProcessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkplaceProcessId");

                    b.ToTable("Workbenches");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.WorkbenchWorkplaceHostDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Configuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkbenchId")
                        .HasColumnType("int");

                    b.Property<int>("WorkplaceHostDeviceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkbenchId");

                    b.HasIndex("WorkplaceHostDeviceId");

                    b.ToTable("WorkbenchDeviceConfigurations");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Workplace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workplaces");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.WorkplaceHostDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("HostDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("WorkplaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HostDeviceId");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("WorkplaceHostDevices");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.WorkplaceProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<int>("WorkplaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("WorkplaceProcesses");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Audit", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.Profile", "Profile")
                        .WithMany("Audits")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.AuditCriterion", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.AuditZone", "Zone")
                        .WithMany("Criteria")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.AuditZone", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.Audit", "Audit")
                        .WithMany("Zones")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.HostDevice", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.Device", "Device")
                        .WithMany("Hosts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.Host", "Host")
                        .WithMany("Devices")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Operation", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.Workbench", "Workbench")
                        .WithMany()
                        .HasForeignKey("WorkbenchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workbench");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.OperationHostDevice", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.HostDevice", "HostDevice")
                        .WithMany()
                        .HasForeignKey("HostDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.Operation", "Operation")
                        .WithMany("Devices")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostDevice");

                    b.Navigation("Operation");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Profile", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.Process", "Process")
                        .WithMany("Profiles")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.ProfilePoint", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.Profile", "Profile")
                        .WithMany("Points")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Record", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.OperationHostDevice", "Device")
                        .WithMany()
                        .HasForeignKey("OperationHostDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Workbench", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.WorkplaceProcess", "WorkplaceProcess")
                        .WithMany("Workbenches")
                        .HasForeignKey("WorkplaceProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkplaceProcess");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.WorkbenchWorkplaceHostDevice", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.Workbench", "Workbench")
                        .WithMany("DeviceConfigurations")
                        .HasForeignKey("WorkbenchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.WorkplaceHostDevice", "WorkplaceHostDevice")
                        .WithMany()
                        .HasForeignKey("WorkplaceHostDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workbench");

                    b.Navigation("WorkplaceHostDevice");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.WorkplaceHostDevice", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.HostDevice", "HostDevice")
                        .WithMany()
                        .HasForeignKey("HostDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.Workplace", "Workplace")
                        .WithMany("Devices")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostDevice");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.WorkplaceProcess", b =>
                {
                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microprojects.Edm.Ui.Technologies.Models.Workplace", "Workplace")
                        .WithMany("Processes")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Audit", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.AuditZone", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Device", b =>
                {
                    b.Navigation("Hosts");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Host", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Operation", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Process", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Profile", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("Points");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Workbench", b =>
                {
                    b.Navigation("DeviceConfigurations");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.Workplace", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Processes");
                });

            modelBuilder.Entity("Microprojects.Edm.Ui.Technologies.Models.WorkplaceProcess", b =>
                {
                    b.Navigation("Workbenches");
                });
#pragma warning restore 612, 618
        }
    }
}
